export const SET_TAAS_SUB_NON_PROXY_PAGINATOR =
  "SET_TAAS_SUB_NON_PROXY_PAGINATOR";
export const SET_TAAS_SUB_PROXY_PAGINATOR = "SET_TAAS_SUB_PROXY_PAGINATOR";
export const SET_CLUSTER_SUB_PAGINATOR = "SET_CLUSTER_SUB_PAGINATOR";

export const SET_TAAS_SUB_PROXY_SORTER = "SET_TAAS_SUB_PROXY_SORTER";
export const SET_CLUSTER_SUB_SORTER = "SET_CLUSTER_SUB_SORTER";

export const SET_TAAS_SUB_PROXY_FILTER = "SET_TAAS_SUB_PROXY_FILTER";
export const SET_CLUSTER_SUB_FILTER = "SET_CLUSTER_SUB_FILTER";

export const SET_TAAS_SUB_NON_PROXY_DATA = "SET_TAAS_SUB_NON_PROXY_DATA";
export const SET_TAAS_SUB_PROXY_DATA = "SET_TAAS_SUB_PROXY_DATA";
export const SET_CLUSTER_SUB_DATA = "SET_CLUSTER_SUB_DATA";
export const SET_SELECTED_SIDER_KEY = "SET_SELECTED_SIDER_KEY";
