export const SET_TAAS_SUB_NON_PROXY_PAGINATOR =
  "SET_TAAS_SUB_NON_PROXY_PAGINATOR";
export const SET_TAAS_SUB_PROXY_PAGINATOR = "SET_TAAS_SUB_PROXY_PAGINATOR";
export const SET_MPS_SUB_PAGINATOR = "SET_MPS_SUB_PAGINATOR";

export const SET_TAAS_SUB_PROXY_SORTER = "SET_TAAS_SUB_PROXY_SORTER";

export const SET_TAAS_SUB_PROXY_FILTER = "SET_TAAS_SUB_PROXY_FILTER";

export const SET_TAAS_SUB_NON_PROXY_DATA = "SET_TAAS_SUB_NON_PROXY_DATA";
export const SET_TAAS_SUB_PROXY_DATA = "SET_TAAS_SUB_PROXY_DATA";
